services:
  dotnetfp:
    build: .
    container_name: dotnetfileportal_api
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DownloadPath=/app/files
    ports:
      - "5000:5000"
    networks:
      file_upload_network:
        ipv4_address: 172.16.0.4
    volumes:
      - dotnetfp_files:/app/files
    depends_on:
      - fileuploaddb
  fileuploaddb:
    image: postgres:14.18-bookworm
    container_name: postgres_fileupload_db
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
      - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      file_upload_network:
        ipv4_address: 172.16.0.3
    restart: always

volumes:
  dotnetfp_files:

networks:
  file_upload_network:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 172.16.0.0/18
          gateway: 172.16.0.1
    